package com.lucasalfare.flgf.core

import com.badlogic.gdx.ApplicationAdapter
import com.badlogic.gdx.Gdx
import com.badlogic.gdx.Input
import com.badlogic.gdx.graphics.GL20
import com.badlogic.gdx.graphics.OrthographicCamera
import com.badlogic.gdx.graphics.g2d.BitmapFont
import com.badlogic.gdx.graphics.g2d.SpriteBatch
import com.badlogic.gdx.utils.TimeUtils
import java.io.InputStream

// Totally basic skeleton for the game generated By IA
class GuitarFlashGame : ApplicationAdapter() {

  private lateinit var batch: SpriteBatch
  private lateinit var font: BitmapFont
  private lateinit var camera: OrthographicCamera

  private lateinit var engine: GameEngine

  private var startTime: Long = 0

  // Input state
  // private val pressed = mutableSetOf<Int>()
  private val lastPressed = mutableSetOf<Int>()

  override fun create() {
    batch = SpriteBatch()
    font = BitmapFont()
    camera = OrthographicCamera()
    camera.setToOrtho(false, 800f, 600f)

    // Load XML from resources
    val input: InputStream = Gdx.files.internal("aux_song.xml").read()
    val song = SongXmlParser.parse(input)

    engine = GameEngine(song.notes, hitWindow = 120)

    startTime = TimeUtils.millis()
  }

  override fun render() {
    val currentTime = TimeUtils.millis() - startTime

    val input = buildInput()

    engine.tick(input, currentTime)

    Gdx.gl.glClearColor(0f, 0f, 0f, 1f)
    Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT)

    camera.update()
    batch.projectionMatrix = camera.combined

    batch.begin()

    drawLanes()
    drawNotes(currentTime)
    drawHUD()

    batch.end()
  }

  // using my own classic ET-UIO keys configuration
  private fun buildInput(): PlayerInput {
    val currentPressed = mutableSetOf<Int>()

    if (Gdx.input.isKeyPressed(Input.Keys.E)) currentPressed.add(0)
    if (Gdx.input.isKeyPressed(Input.Keys.T)) currentPressed.add(1)
    if (Gdx.input.isKeyPressed(Input.Keys.U)) currentPressed.add(2)
    if (Gdx.input.isKeyPressed(Input.Keys.I)) currentPressed.add(3)
    if (Gdx.input.isKeyPressed(Input.Keys.O)) currentPressed.add(4)

    val justPressed = currentPressed.filter { it !in lastPressed }.toSet()

    lastPressed.clear()
    lastPressed.addAll(currentPressed)

    return PlayerInput(
      pressedFrets = currentPressed,
      justPressedFrets = justPressed,
      activateSpecial = Gdx.input.isKeyPressed(Input.Keys.SPACE)
    )
  }

  private fun drawLanes() {
    // TODO
  }

  private fun drawNotes(currentTime: Long) {
    // TODO
  }

  private fun drawHUD() {
    font.draw(batch, "Score: ${engine.score.score}", 20f, 580f)
    font.draw(batch, "Combo: ${engine.score.combo}", 20f, 550f)
    font.draw(batch, "Mult: ${engine.score.multiplier}", 20f, 520f)
    font.draw(batch, "Energy: ${engine.special.energy}", 20f, 490f)
  }

  override fun dispose() {
    batch.dispose()
    font.dispose()
  }
}